[font]
size = 15

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.normal]
family = "Inconsolata"
style = "Light"

# transfer this key binding to the shell as escaped (tmux pane navigation)
[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[window]
opacity = 0.97
